In [4]:
from hmmaudio.utils import load_all_data, predict_label, train_hmm
from hmmaudio.eval import evaluate_models
import numpy as np

# HMMAudio Demo

This notebook demonstrates how to train and evaluate Hidden Markov Models for audio emotion classification using diagonal covariance matrices.

## Quick Start

With hmmaudio.application, the code is simple and straightforward. You can train a model with just a few lines of code:

In [29]:
from hmmaudio.application import EmotionIdentifier

train_path = "data/train"
test_path = "data/test"
model = EmotionIdentifier()
model.train(train_path, limit=10)
print("Trained model with 10 samples per class")

Extracting audio features...


Processing Happy: 100%|██████████| 10/10 [00:00<00:00, 162.56it/s]


Happy: Loaded 10 files


Processing Sad: 100%|██████████| 10/10 [00:00<00:00, 219.21it/s]


Sad: Loaded 10 files


Processing Fear: 100%|██████████| 10/10 [00:00<00:00, 217.03it/s]


Fear: Loaded 10 files


Processing Neutral: 100%|██████████| 10/10 [00:00<00:00, 112.11it/s]


Neutral: Loaded 10 files


Processing Anger: 100%|██████████| 10/10 [00:00<00:00, 212.96it/s]


Anger: Loaded 10 files


Processing Disgust: 100%|██████████| 10/10 [00:00<00:00, 206.30it/s]


Disgust: Loaded 10 files
Audio features Extracted.
Training HMMs...
Training HMM for Happy
Iteration 1/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 28.77it/s]


Iteration 2/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 28.53it/s]


Iteration 3/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 25.10it/s]


Iteration 4/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 26.59it/s]


Iteration 5/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 27.82it/s]


Iteration 6/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 25.40it/s]


Iteration 7/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 28.00it/s]


Iteration 8/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 28.08it/s]


Iteration 9/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 26.01it/s]


Iteration 10/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 27.72it/s]


Training HMM for Sad
Iteration 1/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 29.70it/s]


Iteration 2/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 29.84it/s]


Iteration 3/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 26.62it/s]


Iteration 4/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 29.75it/s]


Iteration 5/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 28.53it/s]


Iteration 6/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 26.35it/s]


Iteration 7/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 28.15it/s]


Iteration 8/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 28.46it/s]


Iteration 9/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 25.55it/s]


Iteration 10/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 28.44it/s]


Training HMM for Fear
Iteration 1/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 29.16it/s]


Iteration 2/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 29.10it/s]


Iteration 3/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 25.56it/s]


Iteration 4/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 29.16it/s]


Iteration 5/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 29.41it/s]


Iteration 6/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 30.11it/s]


Iteration 7/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 29.73it/s]


Iteration 8/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 26.37it/s]


Iteration 9/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 30.11it/s]


Iteration 10/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 29.14it/s]


Training HMM for Neutral
Iteration 1/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 28.43it/s]


Iteration 2/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 25.13it/s]


Iteration 3/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 28.43it/s]


Iteration 4/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 28.13it/s]


Iteration 5/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 28.33it/s]


Iteration 6/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 25.18it/s]


Iteration 7/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 28.02it/s]


Iteration 8/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 27.74it/s]


Iteration 9/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 23.20it/s]


Iteration 10/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 26.98it/s]


Training HMM for Anger
Iteration 1/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 28.46it/s]


Iteration 2/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 25.49it/s]


Iteration 3/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 27.74it/s]


Iteration 4/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 28.43it/s]


Iteration 5/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 25.69it/s]


Iteration 6/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 29.56it/s]


Iteration 7/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 29.64it/s]


Iteration 8/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 29.31it/s]


Iteration 9/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 25.05it/s]


Iteration 10/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 28.61it/s]


Training HMM for Disgust
Iteration 1/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 28.58it/s]


Iteration 2/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 25.61it/s]


Iteration 3/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 28.76it/s]


Iteration 4/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 28.11it/s]


Iteration 5/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 24.65it/s]


Iteration 6/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 27.97it/s]


Iteration 7/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 27.34it/s]


Iteration 8/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 26.95it/s]


Iteration 9/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 24.69it/s]


Iteration 10/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 28.69it/s]

HMMs trained.
Trained model with 10 samples per class


In [27]:
train_acc, train_cm = model.evaluate(train_path, limit=10)
test_acc, test_cm = model.evaluate(test_path, limit=10)
print(f"Train accuracy: {train_acc}")
print(f"Test accuracy: {test_acc}")
print(f"Train confusion matrix:\n{train_cm}")
print(f"Test confusion matrix:\n{test_cm}")

Extracting audio features...


Processing Happy: 100%|██████████| 10/10 [00:00<00:00, 141.57it/s]


Happy: Loaded 10 files


Processing Sad: 100%|██████████| 10/10 [00:00<00:00, 203.37it/s]


Sad: Loaded 10 files


Processing Fear: 100%|██████████| 10/10 [00:00<00:00, 211.08it/s]


Fear: Loaded 10 files


Processing Neutral: 100%|██████████| 10/10 [00:00<00:00, 202.51it/s]


Neutral: Loaded 10 files


Processing Anger: 100%|██████████| 10/10 [00:00<00:00, 127.46it/s]


Anger: Loaded 10 files


Processing Disgust: 100%|██████████| 10/10 [00:00<00:00, 201.33it/s]


Disgust: Loaded 10 files
Audio features Extracted.
Evaluating HMMs...


Evaluating Disgust: 100%|██████████| 10/10 [00:00<00:00, 13.73it/s]


Evaluation complete.
Extracting audio features...


Processing Happy: 100%|██████████| 10/10 [00:00<00:00, 103.49it/s]


Happy: Loaded 10 files


Processing Sad: 100%|██████████| 10/10 [00:00<00:00, 114.26it/s]


Sad: Loaded 10 files


Processing Fear: 100%|██████████| 10/10 [00:00<00:00, 117.18it/s]


Fear: Loaded 10 files


Processing Neutral: 100%|██████████| 10/10 [00:00<00:00, 123.16it/s]


Neutral: Loaded 10 files


Processing Anger: 100%|██████████| 10/10 [00:00<00:00, 110.53it/s]


Anger: Loaded 10 files


Processing Disgust: 100%|██████████| 10/10 [00:00<00:00, 69.04it/s]


Disgust: Loaded 10 files
Audio features Extracted.
Evaluating HMMs...


Evaluating Disgust: 100%|██████████| 10/10 [00:01<00:00,  9.26it/s]

Evaluation complete.
Train accuracy: 0.75
Test accuracy: 0.16666666666666666
Train confusion matrix:
[[10  0  0  0  0  0]
 [ 0  7  0  0  0  3]
 [ 1  0  5  0  1  3]
 [ 0  0  2  5  0  3]
 [ 0  0  0  0 10  0]
 [ 1  0  1  0  0  8]]
Test confusion matrix:
[[ 0  0  0  0 10  0]
 [ 1  0  0  0  9  0]
 [ 1  0  0  0  9  0]
 [ 0  0  0  0 10  0]
 [ 0  0  0  0 10  0]
 [ 0  0  0  0 10  0]]


## Break down

Here is a breakdown of the pipeline:

### Load data

In [5]:
# Define paths
TRAIN_DATA_PATH = "./data/train"
TEST_DATA_PATH = "./data/test"

# Load training and test data
print("Loading training data...")
train_features, train_files = load_all_data(TRAIN_DATA_PATH, limit=10,              
                include_mfcc=True,
                include_delta=True,
                include_delta2=True,
                include_energy=True,
                num_cepstral=13,
                frame_size=0.025,
                frame_stride=0.01)
print("\nLoading test data...")
test_features, test_files = load_all_data(TEST_DATA_PATH, limit=10, 
                include_mfcc=True,
                include_delta=True,
                include_delta2=True,
                include_energy=True,
                num_cepstral=13,
                frame_size=0.025,
                frame_stride=0.01)

Loading training data...


Processing Happy: 100%|██████████| 10/10 [00:00<00:00, 59.98it/s]


Happy: Loaded 10 files


Processing Sad: 100%|██████████| 10/10 [00:00<00:00, 122.09it/s]


Sad: Loaded 10 files


Processing Fear: 100%|██████████| 10/10 [00:00<00:00, 119.55it/s]


Fear: Loaded 10 files


Processing Neutral: 100%|██████████| 10/10 [00:00<00:00, 118.37it/s]


Neutral: Loaded 10 files


Processing Anger: 100%|██████████| 10/10 [00:00<00:00, 120.59it/s]


Anger: Loaded 10 files


Processing Disgust: 100%|██████████| 10/10 [00:00<00:00, 121.55it/s]


Disgust: Loaded 10 files

Loading test data...


Processing Happy:   0%|          | 0/10 [00:00<?, ?it/s]/Users/xgao/Documents/GitHub/HMMAudio/hmmaudio/features.py:25: WavFileWarning: Chunk (non-data) not understood, skipping it.
  sample_rate, audio = wavfile.read(file_path)
Processing Happy: 100%|██████████| 10/10 [00:00<00:00, 44.13it/s]


Happy: Loaded 10 files


Processing Sad: 100%|██████████| 10/10 [00:00<00:00, 48.23it/s]


Sad: Loaded 10 files


Processing Fear: 100%|██████████| 10/10 [00:00<00:00, 62.70it/s]


Fear: Loaded 10 files


Processing Neutral: 100%|██████████| 10/10 [00:00<00:00, 59.00it/s]


Neutral: Loaded 10 files


Processing Anger: 100%|██████████| 10/10 [00:00<00:00, 58.93it/s]


Anger: Loaded 10 files


Processing Disgust: 100%|██████████| 10/10 [00:00<00:00, 45.14it/s]

Disgust: Loaded 10 files


### Train Continuous HMMs with Diagonal Covariance

We'll use diagonal covariance matrices instead of full covariance matrices for faster training.

In [6]:
# Set HMM parameters
n_states = 5
n_features = 1
for features in train_features.values():
    n_features = features[0].shape[1]  # Number of features
    break  # Only need to check the first one
max_iter = 10  # Number of Baum-Welch iterations

# Train HMMs with diagonal covariance (faster)
hmm_models = train_hmm(
    train_features, 
    n_states=n_states, 
    n_symbols=n_features,
    max_iter=max_iter,
    continuous = True,  # Use continuous HMM
    diagonal_covariance=True,  # Use diagonal covariance for speed,
)

Training HMM for Happy
Iteration 1/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 16.55it/s]


Iteration 2/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 15.19it/s]


Iteration 3/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 16.56it/s]


Iteration 4/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 15.26it/s]


Iteration 5/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 16.15it/s]


Iteration 6/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 14.41it/s]


Iteration 7/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 15.48it/s]


Iteration 8/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 15.02it/s]


Iteration 9/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 16.34it/s]


Iteration 10/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 14.27it/s]


Training HMM for Sad
Iteration 1/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 15.64it/s]


Iteration 2/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 16.70it/s]


Iteration 3/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 15.96it/s]


Iteration 4/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 17.27it/s]


Iteration 5/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 16.10it/s]


Iteration 6/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 17.23it/s]


Iteration 7/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 17.27it/s]


Iteration 8/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 15.95it/s]


Iteration 9/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 16.90it/s]


Iteration 10/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 16.01it/s]


Training HMM for Fear
Iteration 1/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 17.20it/s]


Iteration 2/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 16.10it/s]


Iteration 3/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 17.19it/s]


Iteration 4/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 15.93it/s]


Iteration 5/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 17.19it/s]


Iteration 6/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 16.07it/s]


Iteration 7/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 17.20it/s]


Iteration 8/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 17.24it/s]


Iteration 9/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 16.00it/s]


Iteration 10/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 17.25it/s]


Training HMM for Neutral
Iteration 1/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 15.13it/s]


Iteration 2/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 16.44it/s]


Iteration 3/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 15.42it/s]


Iteration 4/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 16.53it/s]


Iteration 5/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 15.39it/s]


Iteration 6/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 16.54it/s]


Iteration 7/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 15.35it/s]


Iteration 8/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 16.55it/s]


Iteration 9/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 15.48it/s]


Iteration 10/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 16.53it/s]


Training HMM for Anger
Iteration 1/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 15.74it/s]


Iteration 2/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 17.25it/s]


Iteration 3/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 15.57it/s]


Iteration 4/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 13.85it/s]


Iteration 5/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 14.27it/s]


Iteration 6/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 15.76it/s]


Iteration 7/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 16.95it/s]


Iteration 8/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 16.31it/s]


Iteration 9/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 16.82it/s]


Iteration 10/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 13.91it/s]


Training HMM for Disgust
Iteration 1/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 15.05it/s]


Iteration 2/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 14.90it/s]


Iteration 3/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 16.13it/s]


Iteration 4/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 14.82it/s]


Iteration 5/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 16.23it/s]


Iteration 6/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 14.98it/s]


Iteration 7/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 16.62it/s]


Iteration 8/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 15.31it/s]


Iteration 9/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 16.80it/s]


Iteration 10/10


Baum-Welch Training Progress: 100%|██████████| 10/10 [00:00<00:00, 15.50it/s]


### Evaluate Models

Now we'll evaluate the trained HMM models on both the training and test sets.
We'll use the new score method to calculate the log-likelihood of each sequence and normalize by sequence length.

In [7]:
# Evaluate on training set
print("\nEvaluating on training set...")
train_accuracy, train_cm, _, _, _ = evaluate_models(
    hmm_models, 
    train_features,
    normalize_by_length=True  # Normalize by sequence length to handle variable-length audio
)
print(f"Train Accuracy: {train_accuracy:.2f}")
print("Train Confusion Matrix:")
print(train_cm)

# Evaluate on test set
print("\nEvaluating on test set...")
test_accuracy, test_cm, _, _, _ = evaluate_models(
    hmm_models, 
    test_features, 
    normalize_by_length=True
)
print(f"Test Accuracy: {test_accuracy:.2f}")
print("Test Confusion Matrix:")
print(test_cm)


Evaluating on training set...
Evaluating HMMs...


Evaluating Disgust: 100%|██████████| 10/10 [00:01<00:00,  7.71it/s]


Evaluation complete.
Train Accuracy: 0.77
Train Confusion Matrix:
[[ 9  0  0  0  1  0]
 [ 0  7  1  2  0  0]
 [ 2  2  5  1  0  0]
 [ 0  0  1  9  0  0]
 [ 0  0  0  0 10  0]
 [ 1  2  0  1  0  6]]

Evaluating on test set...
Evaluating HMMs...


Evaluating Disgust: 100%|██████████| 10/10 [00:01<00:00,  5.45it/s]

Evaluation complete.
Test Accuracy: 0.17
Test Confusion Matrix:
[[ 0  0  0  0 10  0]
 [ 1  0  0  0  9  0]
 [ 1  0  0  0  9  0]
 [ 0  0  0  0 10  0]
 [ 0  0  0  0 10  0]
 [ 0  0  0  0 10  0]]


### Example: Classify a Single Audio Sample

Let's test the model on a single audio sample and print the scores for each emotion.

In [8]:
# Choose a sample from the test set
true_emotion = "Anger"
sample_index = 5  # Choose any sample index
sample_features = test_features[true_emotion][sample_index]

# Predict using utility function
predicted_emotion, scores = predict_label(hmm_models, sample_features)

# Print results
print(f"True emotion: {true_emotion}")
print(f"Predicted emotion: {predicted_emotion}")
print("\nScores for each emotion (log-likelihood/frame, higher is better):")

# Normalize scores by sequence length for fair comparison
normalized_scores = {emotion: score/len(sample_features) for emotion, score in scores.items()}

# Sort and print scores from highest to lowest
for emotion, score in sorted(normalized_scores.items(), key=lambda x: x[1], reverse=True):
    print(f"{emotion}: {score:8.2f}")

True emotion: Anger
Predicted emotion: Anger

Scores for each emotion (log-likelihood/frame, higher is better):
Anger:    -5.98
Happy:   -12.23
Disgust:   -14.50
Fear:   -15.28
Neutral:   -18.04
Sad:   -22.44


## Wrap up

This is a demonstration of the performance of hmmaudio pipeline on the whole dataset.

In [14]:
TRAIN_DATA_PATH = "./data/train"
TEST_DATA_PATH = "./data/test"
n_states = 5


# Load training and test data
print("Loading training data...")
train_features, train_files = load_all_data(TRAIN_DATA_PATH,              
                include_mfcc=True,
                include_delta=True,
                include_delta2=True,
                include_energy=True,
                num_cepstral=13,
                frame_size=0.025,
                frame_stride=0.01)
print("\nLoading test data...")
test_features, test_files = load_all_data(TEST_DATA_PATH, 
                include_mfcc=True,
                include_delta=True,
                include_delta2=True,
                include_energy=True,
                num_cepstral=13,
                frame_size=0.025,
                frame_stride=0.01)

n_features = train_features["Anger"][0].shape[1]  # Number of features

hmm_models_full_iter10 = train_hmm(
    train_features, 
    n_states=n_states, 
    n_symbols=n_features,
    max_iter=10,
    continuous = True,  # Use continuous HMM
    diagonal_covariance=True,  # Use diagonal covariance for speed,
)

Loading training data...
Processing Happy: 100%|██████████| 1271/1271 [00:08<00:00, 142.25it/s]
Happy: Loaded 1271 files
Processing Sad: 100%|██████████| 1271/1271 [00:10<00:00, 125.04it/s]
Sad: Loaded 1271 files
Processing Fear: 100%|██████████| 1271/1271 [00:10<00:00, 125.31it/s]
Fear: Loaded 1271 files
Processing Neutral: 100%|██████████| 1087/1087 [00:08<00:00, 121.49it/s]
Neutral: Loaded 1087 files
Processing Anger: 100%|██████████| 1271/1271 [00:09<00:00, 131.03it/s]
Anger: Loaded 1271 files
Processing Disgust: 100%|██████████| 1271/1271 [00:12<00:00, 105.36it/s]
Disgust: Loaded 1271 files

Loading test data...
Processing Happy: 100%|██████████| 48/48 [00:00<00:00, 68.73it/s]
Happy: Loaded 48 files
Processing Sad: 100%|██████████| 48/48 [00:00<00:00, 72.95it/s]
Sad: Loaded 48 files
Processing Fear: 100%|██████████| 48/48 [00:00<00:00, 67.09it/s]
Fear: Loaded 48 files
Processing Neutral: 100%|██████████| 48/48 [00:00<00:00, 78.42it/s]
Neutral: Loaded 48 files
Processing Anger: 100

In [30]:
# Evaluate on training set
print("\nEvaluating on training set")
train_accuracy, train_cm, _, _, _ = evaluate_models(
    hmm_models_full_iter10, 
    train_features, 
    train_files,
)
print(f"Train Accuracy: {train_accuracy:.2f}")
print("Train Confusion Matrix:")
print(train_cm)
# Evaluate on test set
print("\nEvaluating on test set")
test_accuracy, test_cm, _, _, _ = evaluate_models(
    hmm_models_full_iter10, 
    test_features, 
    test_files
)
print(f"Test Accuracy: {test_accuracy:.2f}")
print("Test Confusion Matrix:")
print(test_cm)

# Save the trained HMM models to an npz file

np.savez("hmm_models_full_iter10.npz", hmm_models=hmm_models_full_iter10)
print("HMM models saved to hmm_models_full_iter10.npz")


Evaluating on training set
Evaluating HMMs...


Evaluating Disgust: 100%|██████████| 1271/1271 [01:40<00:00, 12.65it/s]


Evaluation complete.
Train Accuracy: 0.40
Train Confusion Matrix:
[[423  53  96 253 383  63]
 [ 46 745 138 268  28  46]
 [166 309 209 269 286  32]
 [173 143 148 496  40  87]
 [150   8  25  37 985  66]
 [212 255 134 310 209 151]]

Evaluating on test set
Evaluating HMMs...


Evaluating Disgust: 100%|██████████| 48/48 [00:05<00:00,  9.26it/s]

Evaluation complete.
Test Accuracy: 0.17
Test Confusion Matrix:
[[ 0  0 22  0 26  0]
 [ 0  0 17  0 31  0]
 [ 0  0 21  0 27  0]
 [ 0  1 14  0 33  0]
 [ 0  3 16  0 29  0]
 [ 0  0 13  0 35  0]]
HMM models saved to hmm_models_full_iter10.npz
